---
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.5
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  broker:
    image: confluentinc/cp-kafka:7.9.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra-data:/var/lib/cassandra

  cassandra-init:
    image: cassandra:latest
    depends_on:
      - cassandra
    entrypoint: >
      bash -ce "sleep 20 &&
      echo \"CREATE KEYSPACE IF NOT EXISTS example
      WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};\" |
      cqlsh cassandra 9042"
volumes:
  mongodb_data:
  redis_data:
  cassandra-data:
